# Generated by Django 2.0.5 on 2018-07-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=80)),
                ('title', models.CharField(choices=[('good', 'good'), ('best', 'best')], max_length=80)),
            ],
        ),
    ]
