# Generated by Django 2.0.5 on 2018-07-21 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0003_auto_20180721_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eCommerce.Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eCommerce.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='Inserted_On',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_On',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
